name: "Javascript workflow1"

on:
  push:
    branches:
      - master   # Trigger workflow on push to master branch
  pull_request:
    branches:
      - master   # Trigger workflow when a PR is created for master branch

jobs:
  on-push:
    if: github.event_name == 'push'  
    # Run only for push events
    runs-on: ubuntu-latest           # Run the job on the latest Ubuntu environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # This step checks out your code from the repo

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Setup Node.js version 16

      - name: Install Dependencies
        run: npm install  # Install project dependencies defined in package.json

      - name: Run Code (Check for Errors)
        run: node index.js  # Run index.js file to check for errors

      - name: Echo Success
        run: echo "Running on master successfully"  # Echo success message

  on-pull-request:
    if: github.event_name == 'pull_request'  
    # Run only for pull request events
    runs-on: ubuntu-latest                   # Run the job on the latest Ubuntu environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checkout code from the repo

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Setup Node.js version 16

      - name: Run Code (Check for Errors)
        run: node index.js  # Run index.js to check for errors

      - name: Echo PR Success
        run: echo "Running on pull request successfully"  # Echo success message for PR
